theme: osuny
_merge: deep
params:
  breadcrumb:
    position: after-hero
  search:
    active: true
    positions:
      - footer
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/icone.svg"