theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: after-hero
  search:
    active: true
    positions:
      - footer
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/icone.svg"